// Code generated by goctl. DO NOT EDIT!
package model

import (
	"context"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
)

type catPopularityModel interface {
	Insert(ctx context.Context, data *CatPopularity) error
	FindOne(ctx context.Context, id string) (*CatPopularity, error)
	Update(ctx context.Context, data *CatPopularity) error
	Delete(ctx context.Context, id string) error
}

type defaultCatPopularityModel struct {
	conn *mon.Model
}

func newDefaultCatPopularityModel(conn *mon.Model) *defaultCatPopularityModel {
	return &defaultCatPopularityModel{conn: conn}
}

func (m *defaultCatPopularityModel) Insert(ctx context.Context, data *CatPopularity) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	return err
}

func (m *defaultCatPopularityModel) FindOne(ctx context.Context, id string) (*CatPopularity, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, ErrInvalidObjectId
	}

	var data CatPopularity

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCatPopularityModel) Update(ctx context.Context, data *CatPopularity) error {
	data.UpdateAt = time.Now()

	_, err := m.conn.ReplaceOne(ctx, bson.M{"_id": data.ID}, data)
	return err
}

func (m *defaultCatPopularityModel) Delete(ctx context.Context, id string) error {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return ErrInvalidObjectId
	}

	_, err = m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	return err
}
