// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.19.4
// source: like.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DoLikeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// 点赞的目标ID，可以是评论ID，文章ID等
	TargetId string `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	// 点赞的类型，点赞评论、点赞文章等都可以视为点赞的不同类型（类型常量定义在like/types.go）
	Type int64 `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	// 对象所关联的ID，比如评论点赞对应文章ID等
	AssociatedId string `protobuf:"bytes,4,opt,name=associatedId,proto3" json:"associatedId,omitempty"`
}

func (x *DoLikeReq) Reset() {
	*x = DoLikeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoLikeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoLikeReq) ProtoMessage() {}

func (x *DoLikeReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoLikeReq.ProtoReflect.Descriptor instead.
func (*DoLikeReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{0}
}

func (x *DoLikeReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DoLikeReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *DoLikeReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *DoLikeReq) GetAssociatedId() string {
	if x != nil {
		return x.AssociatedId
	}
	return ""
}

type DoLikeResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoLikeResp) Reset() {
	*x = DoLikeResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoLikeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoLikeResp) ProtoMessage() {}

func (x *DoLikeResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoLikeResp.ProtoReflect.Descriptor instead.
func (*DoLikeResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{1}
}

type GetUserLikedReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId   string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TargetId string `protobuf:"bytes,2,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Type     int64  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetUserLikedReq) Reset() {
	*x = GetUserLikedReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikedReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedReq) ProtoMessage() {}

func (x *GetUserLikedReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedReq.ProtoReflect.Descriptor instead.
func (*GetUserLikedReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserLikedReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserLikedReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetUserLikedReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetUserLikedResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Liked bool `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
}

func (x *GetUserLikedResp) Reset() {
	*x = GetUserLikedResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserLikedResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLikedResp) ProtoMessage() {}

func (x *GetUserLikedResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLikedResp.ProtoReflect.Descriptor instead.
func (*GetUserLikedResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserLikedResp) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

type GetTargetLikesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TargetId string `protobuf:"bytes,1,opt,name=targetId,proto3" json:"targetId,omitempty"`
	Type     int64  `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *GetTargetLikesReq) Reset() {
	*x = GetTargetLikesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTargetLikesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetLikesReq) ProtoMessage() {}

func (x *GetTargetLikesReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetLikesReq.ProtoReflect.Descriptor instead.
func (*GetTargetLikesReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{4}
}

func (x *GetTargetLikesReq) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *GetTargetLikesReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetTargetLikesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *GetTargetLikesResp) Reset() {
	*x = GetTargetLikesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTargetLikesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetLikesResp) ProtoMessage() {}

func (x *GetTargetLikesResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetLikesResp.ProtoReflect.Descriptor instead.
func (*GetTargetLikesResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{5}
}

func (x *GetTargetLikesResp) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// 获取 top k
type GetTopKReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K     int64  `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
	Type  string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Range int64  `protobuf:"varint,3,opt,name=range,proto3" json:"range,omitempty"`
}

func (x *GetTopKReq) Reset() {
	*x = GetTopKReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopKReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopKReq) ProtoMessage() {}

func (x *GetTopKReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopKReq.ProtoReflect.Descriptor instead.
func (*GetTopKReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{6}
}

func (x *GetTopKReq) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *GetTopKReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetTopKReq) GetRange() int64 {
	if x != nil {
		return x.Range
	}
	return 0
}

type ItemScore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score int64  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *ItemScore) Reset() {
	*x = ItemScore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ItemScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemScore) ProtoMessage() {}

func (x *ItemScore) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemScore.ProtoReflect.Descriptor instead.
func (*ItemScore) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{7}
}

func (x *ItemScore) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetTopKResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item []*ItemScore `protobuf:"bytes,1,rep,name=item,proto3" json:"item,omitempty"`
}

func (x *GetTopKResp) Reset() {
	*x = GetTopKResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTopKResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopKResp) ProtoMessage() {}

func (x *GetTopKResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopKResp.ProtoReflect.Descriptor instead.
func (*GetTopKResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{8}
}

func (x *GetTopKResp) GetItem() []*ItemScore {
	if x != nil {
		return x.Item
	}
	return nil
}

// 增加分数
type AddScoreReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id   string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Val  int64  `protobuf:"varint,3,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AddScoreReq) Reset() {
	*x = AddScoreReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreReq) ProtoMessage() {}

func (x *AddScoreReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreReq.ProtoReflect.Descriptor instead.
func (*AddScoreReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{9}
}

func (x *AddScoreReq) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AddScoreReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddScoreReq) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type AddScoreResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val int64 `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AddScoreResp) Reset() {
	*x = AddScoreResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddScoreResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddScoreResp) ProtoMessage() {}

func (x *AddScoreResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddScoreResp.ProtoReflect.Descriptor instead.
func (*AddScoreResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{10}
}

func (x *AddScoreResp) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type DailyUpdateResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DailyUpdateResp) Reset() {
	*x = DailyUpdateResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyUpdateResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyUpdateResp) ProtoMessage() {}

func (x *DailyUpdateResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyUpdateResp.ProtoReflect.Descriptor instead.
func (*DailyUpdateResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{11}
}

type DailyUpdateReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DailyUpdateReq) Reset() {
	*x = DailyUpdateReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DailyUpdateReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyUpdateReq) ProtoMessage() {}

func (x *DailyUpdateReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyUpdateReq.ProtoReflect.Descriptor instead.
func (*DailyUpdateReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{12}
}

// 获取猫咪人气
type ListCatPopularityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId []string `protobuf:"bytes,1,rep,name=catId,proto3" json:"catId,omitempty"`
}

func (x *ListCatPopularityReq) Reset() {
	*x = ListCatPopularityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatPopularityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatPopularityReq) ProtoMessage() {}

func (x *ListCatPopularityReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatPopularityReq.ProtoReflect.Descriptor instead.
func (*ListCatPopularityReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{13}
}

func (x *ListCatPopularityReq) GetCatId() []string {
	if x != nil {
		return x.CatId
	}
	return nil
}

type CatPop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId      string `protobuf:"bytes,1,opt,name=catId,proto3" json:"catId,omitempty"`
	Popularity int64  `protobuf:"varint,2,opt,name=popularity,proto3" json:"popularity,omitempty"`
}

func (x *CatPop) Reset() {
	*x = CatPop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CatPop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CatPop) ProtoMessage() {}

func (x *CatPop) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CatPop.ProtoReflect.Descriptor instead.
func (*CatPop) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{14}
}

func (x *CatPop) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *CatPop) GetPopularity() int64 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

type ListCatPopularityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cats []*CatPop `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
}

func (x *ListCatPopularityResp) Reset() {
	*x = ListCatPopularityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListCatPopularityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCatPopularityResp) ProtoMessage() {}

func (x *ListCatPopularityResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCatPopularityResp.ProtoReflect.Descriptor instead.
func (*ListCatPopularityResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{15}
}

func (x *ListCatPopularityResp) GetCats() []*CatPop {
	if x != nil {
		return x.Cats
	}
	return nil
}

// 操作猫咪人气
type AddCatPopularityReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CatId string `protobuf:"bytes,1,opt,name=catId,proto3" json:"catId,omitempty"`
	Val   int64  `protobuf:"varint,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (x *AddCatPopularityReq) Reset() {
	*x = AddCatPopularityReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCatPopularityReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCatPopularityReq) ProtoMessage() {}

func (x *AddCatPopularityReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCatPopularityReq.ProtoReflect.Descriptor instead.
func (*AddCatPopularityReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{16}
}

func (x *AddCatPopularityReq) GetCatId() string {
	if x != nil {
		return x.CatId
	}
	return ""
}

func (x *AddCatPopularityReq) GetVal() int64 {
	if x != nil {
		return x.Val
	}
	return 0
}

type AddCatPopularityResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddCatPopularityResp) Reset() {
	*x = AddCatPopularityResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddCatPopularityResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddCatPopularityResp) ProtoMessage() {}

func (x *AddCatPopularityResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddCatPopularityResp.ProtoReflect.Descriptor instead.
func (*AddCatPopularityResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{17}
}

// 查看 topk 猫咪
type ListTopCatReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	K int64 `protobuf:"varint,1,opt,name=k,proto3" json:"k,omitempty"`
}

func (x *ListTopCatReq) Reset() {
	*x = ListTopCatReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopCatReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopCatReq) ProtoMessage() {}

func (x *ListTopCatReq) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopCatReq.ProtoReflect.Descriptor instead.
func (*ListTopCatReq) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{18}
}

func (x *ListTopCatReq) GetK() int64 {
	if x != nil {
		return x.K
	}
	return 0
}

type ListTopCatResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cats []*CatPop `protobuf:"bytes,1,rep,name=cats,proto3" json:"cats,omitempty"`
}

func (x *ListTopCatResp) Reset() {
	*x = ListTopCatResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_like_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTopCatResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopCatResp) ProtoMessage() {}

func (x *ListTopCatResp) ProtoReflect() protoreflect.Message {
	mi := &file_like_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopCatResp.ProtoReflect.Descriptor instead.
func (*ListTopCatResp) Descriptor() ([]byte, []int) {
	return file_like_proto_rawDescGZIP(), []int{19}
}

func (x *ListTopCatResp) GetCats() []*CatPop {
	if x != nil {
		return x.Cats
	}
	return nil
}

var File_like_proto protoreflect.FileDescriptor

var file_like_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6c, 0x69,
	0x6b, 0x65, 0x22, 0x77, 0x0a, 0x09, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73, 0x73, 0x6f, 0x63,
	0x69, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61,
	0x73, 0x73, 0x6f, 0x63, 0x69, 0x61, 0x74, 0x65, 0x64, 0x49, 0x64, 0x22, 0x0c, 0x0a, 0x0a, 0x44,
	0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x59, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x28, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c,
	0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6b, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6c, 0x69, 0x6b, 0x65, 0x64, 0x22, 0x43,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x22, 0x2a, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x44, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70, 0x4b, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a,
	0x01, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x72, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x31, 0x0a, 0x09, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x63, 0x6f,
	0x72, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x32, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x54,
	0x6f, 0x70, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x49, 0x74, 0x65,
	0x6d, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x22, 0x43, 0x0a, 0x0b,
	0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61,
	0x6c, 0x22, 0x20, 0x0a, 0x0c, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x76, 0x61, 0x6c, 0x22, 0x11, 0x0a, 0x0f, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x10, 0x0a, 0x0e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x22, 0x2c, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x06, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x22, 0x39, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61,
	0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x20, 0x0a, 0x04, 0x63, 0x61, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x52, 0x04, 0x63, 0x61, 0x74,
	0x73, 0x22, 0x3d, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c,
	0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x74, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x74, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x76, 0x61, 0x6c,
	0x22, 0x16, 0x0a, 0x14, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x1d, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74,
	0x54, 0x6f, 0x70, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x12, 0x0c, 0x0a, 0x01, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x6b, 0x22, 0x32, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x54,
	0x6f, 0x70, 0x43, 0x61, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x63, 0x61, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x43,
	0x61, 0x74, 0x50, 0x6f, 0x70, 0x52, 0x04, 0x63, 0x61, 0x74, 0x73, 0x32, 0xb9, 0x04, 0x0a, 0x04,
	0x6c, 0x69, 0x6b, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x12, 0x0f,
	0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x6f, 0x4c, 0x69, 0x6b, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69,
	0x6b, 0x65, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x6c, 0x69, 0x6b, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x6b, 0x65, 0x64, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74,
	0x4c, 0x69, 0x6b, 0x65, 0x73, 0x12, 0x17, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c, 0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x18,
	0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x4c,
	0x69, 0x6b, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x07, 0x47, 0x65,
	0x74, 0x54, 0x6f, 0x70, 0x4b, 0x12, 0x10, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x6f, 0x70, 0x4b, 0x52, 0x65, 0x71, 0x1a, 0x11, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x47,
	0x65, 0x74, 0x54, 0x6f, 0x70, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x08,
	0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x11, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e,
	0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x6c, 0x69,
	0x6b, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22,
	0x00, 0x12, 0x3c, 0x0a, 0x0b, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x14, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x61, 0x69, 0x6c, 0x79, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x44, 0x61,
	0x69, 0x6c, 0x79, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61,
	0x72, 0x69, 0x74, 0x79, 0x12, 0x1a, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x43, 0x61, 0x74, 0x50,
	0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12,
	0x4b, 0x0a, 0x10, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72,
	0x69, 0x74, 0x79, 0x12, 0x19, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61,
	0x74, 0x50, 0x6f, 0x70, 0x75, 0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x1a,
	0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x43, 0x61, 0x74, 0x50, 0x6f, 0x70, 0x75,
	0x6c, 0x61, 0x72, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x12, 0x39, 0x0a, 0x0a,
	0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x43, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x6c, 0x69, 0x6b,
	0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x43, 0x61, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x14, 0x2e, 0x6c, 0x69, 0x6b, 0x65, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x6f, 0x70, 0x43, 0x61,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_like_proto_rawDescOnce sync.Once
	file_like_proto_rawDescData = file_like_proto_rawDesc
)

func file_like_proto_rawDescGZIP() []byte {
	file_like_proto_rawDescOnce.Do(func() {
		file_like_proto_rawDescData = protoimpl.X.CompressGZIP(file_like_proto_rawDescData)
	})
	return file_like_proto_rawDescData
}

var file_like_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_like_proto_goTypes = []interface{}{
	(*DoLikeReq)(nil),             // 0: like.DoLikeReq
	(*DoLikeResp)(nil),            // 1: like.DoLikeResp
	(*GetUserLikedReq)(nil),       // 2: like.GetUserLikedReq
	(*GetUserLikedResp)(nil),      // 3: like.GetUserLikedResp
	(*GetTargetLikesReq)(nil),     // 4: like.GetTargetLikesReq
	(*GetTargetLikesResp)(nil),    // 5: like.GetTargetLikesResp
	(*GetTopKReq)(nil),            // 6: like.GetTopKReq
	(*ItemScore)(nil),             // 7: like.ItemScore
	(*GetTopKResp)(nil),           // 8: like.GetTopKResp
	(*AddScoreReq)(nil),           // 9: like.AddScoreReq
	(*AddScoreResp)(nil),          // 10: like.AddScoreResp
	(*DailyUpdateResp)(nil),       // 11: like.DailyUpdateResp
	(*DailyUpdateReq)(nil),        // 12: like.DailyUpdateReq
	(*ListCatPopularityReq)(nil),  // 13: like.ListCatPopularityReq
	(*CatPop)(nil),                // 14: like.CatPop
	(*ListCatPopularityResp)(nil), // 15: like.ListCatPopularityResp
	(*AddCatPopularityReq)(nil),   // 16: like.AddCatPopularityReq
	(*AddCatPopularityResp)(nil),  // 17: like.AddCatPopularityResp
	(*ListTopCatReq)(nil),         // 18: like.ListTopCatReq
	(*ListTopCatResp)(nil),        // 19: like.ListTopCatResp
}
var file_like_proto_depIdxs = []int32{
	7,  // 0: like.GetTopKResp.item:type_name -> like.ItemScore
	14, // 1: like.ListCatPopularityResp.cats:type_name -> like.CatPop
	14, // 2: like.ListTopCatResp.cats:type_name -> like.CatPop
	0,  // 3: like.like.DoLike:input_type -> like.DoLikeReq
	2,  // 4: like.like.GetUserLike:input_type -> like.GetUserLikedReq
	4,  // 5: like.like.GetTargetLikes:input_type -> like.GetTargetLikesReq
	6,  // 6: like.like.GetTopK:input_type -> like.GetTopKReq
	9,  // 7: like.like.AddScore:input_type -> like.AddScoreReq
	12, // 8: like.like.DailyUpdate:input_type -> like.DailyUpdateReq
	13, // 9: like.like.ListCatPopularity:input_type -> like.ListCatPopularityReq
	16, // 10: like.like.AddCatPopularity:input_type -> like.AddCatPopularityReq
	18, // 11: like.like.ListTopCat:input_type -> like.ListTopCatReq
	1,  // 12: like.like.DoLike:output_type -> like.DoLikeResp
	3,  // 13: like.like.GetUserLike:output_type -> like.GetUserLikedResp
	5,  // 14: like.like.GetTargetLikes:output_type -> like.GetTargetLikesResp
	8,  // 15: like.like.GetTopK:output_type -> like.GetTopKResp
	10, // 16: like.like.AddScore:output_type -> like.AddScoreResp
	11, // 17: like.like.DailyUpdate:output_type -> like.DailyUpdateResp
	15, // 18: like.like.ListCatPopularity:output_type -> like.ListCatPopularityResp
	17, // 19: like.like.AddCatPopularity:output_type -> like.AddCatPopularityResp
	19, // 20: like.like.ListTopCat:output_type -> like.ListTopCatResp
	12, // [12:21] is the sub-list for method output_type
	3,  // [3:12] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_like_proto_init() }
func file_like_proto_init() {
	if File_like_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_like_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoLikeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoLikeResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikedReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserLikedResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTargetLikesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTargetLikesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopKReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ItemScore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTopKResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddScoreResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyUpdateResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DailyUpdateReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatPopularityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CatPop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListCatPopularityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCatPopularityReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddCatPopularityResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTopCatReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_like_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTopCatResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_like_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_like_proto_goTypes,
		DependencyIndexes: file_like_proto_depIdxs,
		MessageInfos:      file_like_proto_msgTypes,
	}.Build()
	File_like_proto = out.File
	file_like_proto_rawDesc = nil
	file_like_proto_goTypes = nil
	file_like_proto_depIdxs = nil
}
